let
    Source = Folder.Files("C:\Users\ryanp\OneDrive\Desktop\Capstone Project\2021 Data\og"),
    #"Removed Other Columns" = Table.SelectColumns(Source,{"Content"}),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"ride_id", type text}, {"rideable_type", type text}, {"started_at", type datetime}, {"ended_at", type datetime}, {"start_station_name", type text}, {"start_station_id", type text}, {"end_station_name", type text}, {"end_station_id", type text}, {"start_lat", type number}, {"start_lng", type number}, {"end_lat", type number}, {"end_lng", type number}, {"member_casual", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"ride_id"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns", "started_at", "started_at - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "started_at", "started_at - Copy.1"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "ended_at", "ended_at - Copy"),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Duplicated Column2", "ended_at", "ended_at - Copy.1"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column3",{{"started_at - Copy", type date}, {"ended_at - Copy", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"started_at - Copy", "start_date"}, {"ended_at - Copy", "end_date"}, {"started_at - Copy.1", "start_hour"}, {"ended_at - Copy.1", "end_hour"}}),
    #"Extracted Hour" = Table.TransformColumns(#"Renamed Columns",{{"start_hour", Time.Hour, Int64.Type}, {"end_hour", Time.Hour, Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Extracted Hour", "trip_duration_minutes", each [ended_at]-[started_at]),
    #"Extracted Minutes" = Table.TransformColumns(#"Added Custom",{{"trip_duration_minutes", Duration.Minutes, Int64.Type}}),
    #"Filtered Rows" = Table.SelectRows(#"Extracted Minutes", each [start_station_name] <> null and [start_station_name] <> ""),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [ended_at] <> null and [ended_at] <> ""),
    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [started_at] <> null and [started_at] <> ""),
    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each [rideable_type] <> null and [rideable_type] <> ""),
    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows3", each [start_station_name] <> null and [start_station_name] <> ""),
    #"Filtered Rows5" = Table.SelectRows(#"Filtered Rows4", each [start_station_id] <> null and [start_station_id] <> ""),
    #"Filtered Rows6" = Table.SelectRows(#"Filtered Rows5", each [end_station_name] <> null and [end_station_name] <> ""),
    #"Filtered Rows7" = Table.SelectRows(#"Filtered Rows6", each [end_station_id] <> null and [end_station_id] <> ""),
    #"Filtered Rows8" = Table.SelectRows(#"Filtered Rows7", each [start_lat] <> null and [start_lat] <> ""),
    #"Filtered Rows9" = Table.SelectRows(#"Filtered Rows8", each [start_lng] <> null and [start_lng] <> ""),
    #"Filtered Rows10" = Table.SelectRows(#"Filtered Rows9", each [end_lat] <> null and [end_lat] <> ""),
    #"Filtered Rows11" = Table.SelectRows(#"Filtered Rows10", each [end_lng] <> null and [end_lng] <> ""),
    #"Filtered Rows12" = Table.SelectRows(#"Filtered Rows11", each [member_casual] <> null and [member_casual] <> ""),
    #"Filtered Rows13" = Table.SelectRows(#"Filtered Rows12", each [start_date] <> null and [start_date] <> ""),
    #"Filtered Rows14" = Table.SelectRows(#"Filtered Rows13", each [start_hour] <> null and [start_hour] <> ""),
    #"Filtered Rows15" = Table.SelectRows(#"Filtered Rows14", each [end_date] <> null and [end_date] <> ""),
    #"Filtered Rows16" = Table.SelectRows(#"Filtered Rows15", each [end_hour] <> null and [end_hour] <> ""),
    #"Filtered Rows17" = Table.SelectRows(#"Filtered Rows16", each [trip_duration_minutes] <> null and [trip_duration_minutes] <> ""),
    #"Filtered Rows18" = Table.SelectRows(#"Filtered Rows17", each [trip_duration_minutes] <> null and [trip_duration_minutes] <> "")
in
    #"Filtered Rows18"
